language: ruby
sudo: false
cache: bundler
bundler_args: --without tools benchmarks
script:
  - bundle exec rake spec
before_install:
  - gem install bundler
  - gem update --system
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-9.1.16.0
